version: 2

models:

  - name: stg_customers
    description: Cleaned customer data

    columns:
      - name: customer_id
        description: Primary key of customer
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null

  - name: stg_products
    description: Cleaned product data

    columns:
      - name: product_id
        tests:
          - unique
          - not_null

      - name: price
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned orders

    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id

  - name: stg_order_items
    description: Order line items

    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null

      - name: order_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id

      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id