-- Setup script

-- Create Warehouse
CREATE WAREHOUSE ELT_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE ELT_WH;

-- Create Database
CREATE DATABASE ELT_WAREHOUSE;

USE DATABASE ELT_WAREHOUSE;

-- Create Schemas
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA MARTS;

