-- Setup script

-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS ELT_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE ELT_WH;

-- Create Database
CREATE DATABASE IF NOT EXISTS ELT_WAREHOUSE;

USE DATABASE ELT_WAREHOUSE;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;

