# Snowflake connection secrets for Streamlit dashboard
# Replace the values below with your Snowflake credentials.

[snowflake]
user = "zaynahimran"
password = "Zaynah4959002Zz#"
account = "bjgmffl-rw59312"
warehouse = "COMPUTE_WH"
database = "ELT_WAREHOUSE"
schema = "RAW_MARTS"
role = "ACCOUNTADMIN"